template: presentation.tex
	pdftotex $<

clean:
	@rm *.aux 2> /dev/null || true
	@rm *.nav 2> /dev/null || true
	@rm *.snm 2> /dev/null || true
	@rm *.toc 2> /dev/null || true
	@rm *.vrb 2> /dev/null || true
	@rm *.log 2> /dev/null || true
	@rm *.out 2> /dev/null || true
