
docker:
	docker build -t exo-rust .

exo1:
	docker run exo-rust 'cd /home/docker/1/ && cargo run'

exo2:
	docker run exo-rust 'cd /home/docker/2/ && cargo run'

exo3:
	docker run exo-rust 'cd /home/docker/3/ && cargo run'
